### ISSUE TITLE
External House Placement

### ISSUE THREAD

**Issue by Davnik** [TacoWolf/WolfBot#33]
People should not be able to set the houses of others using "!house set @mention x". This could create issues in the event someone takes later interest in joining a house but is already erroneously in one. An alternative would be to allow headmasters to either free someone from their house or assign them to a new house.

**Comment by takouhai** [comment]
This isn't a feature that's implemented. This doesn't work, it simply triggers [this code](https://github.com/TacoWolf/WolfBot/blob/master/scripts/house_set.js#L18): 

``` js
if (!user.house) {
  col.updateOne({userID: event.userID}, {
    $set: {house: userHouse}
  });
  houseName = helpers.houseDetail(userHouse);
  msg = 'You have successfully been sorted into `';
  msg += houseName + '`, **' + event.user + '** ! `^w^`';
} else {
  houseName = helpers.houseDetail(user.house);
  msg = 'You\'ve already been sorted into `';
  msg += houseName + '`, **' + event.user + '**. >w>';
}
```

This doesn't touch the database and doesn't really do anything. It simply detects that the user is already sorted into a house. For some reason, triggering it with a `userID` inserted into the command associates it with the user mentioned instead of the user who sent the message. I might plan on fixing this, but this bug is not clearly descriptive of it. For now, users can simply _not_ mention a user while using the command.
